config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :comments
  root to:'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new 
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        
    end

    def new
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<%= form_tag(comments_path , method: "post") do %>
    <div class="form-group">
        <%= text_field_tag(:title, nil, placeholder: "Title...", class: "form-control") %>
    </div>
    <div class="form-group">
        <%= text_area_tag(:content ,nil ,placeholder: "Content...", class: "form-control" ) %>
    </div>
    <%= submit_tag "Comment" , class: "btn btn-success btn-block" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<%=  root_path %>">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%= new_post_path %>"> Post <span class="sr-only">(current)</span></a>
            </li>
             <li class="nav-item active">
              <a class="nav-link" href="<%= new_comment_path %>"> Comment <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
    </nav>


    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1> Hello </h1>

app/views/posts/new.html.erb
<%= form_tag(posts_path , method: "post") do %>
    <div class="form-group">
        <%= text_field_tag(:title, nil, placeholder: "Title...", class: "form-control") %>
    </div>
    <div class="form-group">
        <%= text_area_tag(:content ,nil ,placeholder: "Content...", class: "form-control" ) %>
    </div>
    <%= submit_tag "Create" , class: "btn btn-success btn-block" %>
<% end %>